// This file is auto-generated by @hey-api/openapi-ts

export type BodyFinalDocumentServiceGenerateFinalDocument = {
    user: User;
    project_id: string;
};

export type BodyFinalDocumentServiceGetProjectSummary = {
    user: User;
    project_id: string;
};

export type BodyProjectServiceCompleteProject = {
    project_id: string;
};

export type BodyProjectServiceCreateProject = {
    project_name: string;
    description?: string | null;
};

export type BodyProjectServiceDeleteProject = {
    project_id: string;
};

export type BodyProjectServiceGetProject = {
    project_id: string;
};

export type BodyProjectServiceGetProjectExport = {
    project_id: string;
};

export type BodyProjectServiceRefineWithAi = {
    project_id: string;
    step_id: string;
    user_input: string;
    prompt_template_key: string;
};

export type BodyProjectServiceSaveStepData = {
    project_id: string;
    step_id: string;
    step_data: {
        [key: string]: unknown;
    };
};

export type BodyProjectServiceUpdateProject = {
    project_id: string;
    updates: {
        [key: string]: unknown;
    };
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Project = {
    id?: string;
    user_id: string;
    project_name: string;
    description?: string | null;
    status?: string;
    current_step?: number;
    planning_data?: {
        [key: string]: unknown;
    };
    created_at?: string;
    updated_at?: string;
};

export type User = {
    id: string;
    email: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ProjectServiceCreateProjectData = {
    body: BodyProjectServiceCreateProject;
    path?: never;
    query?: never;
    url: '/api/project_service/create_project';
};

export type ProjectServiceCreateProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProjectServiceCreateProjectError = ProjectServiceCreateProjectErrors[keyof ProjectServiceCreateProjectErrors];

export type ProjectServiceCreateProjectResponses = {
    /**
     * Successful Response
     */
    200: Project;
};

export type ProjectServiceCreateProjectResponse = ProjectServiceCreateProjectResponses[keyof ProjectServiceCreateProjectResponses];

export type ProjectServiceGetProjectData = {
    body: BodyProjectServiceGetProject;
    path?: never;
    query?: never;
    url: '/api/project_service/get_project';
};

export type ProjectServiceGetProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProjectServiceGetProjectError = ProjectServiceGetProjectErrors[keyof ProjectServiceGetProjectErrors];

export type ProjectServiceGetProjectResponses = {
    /**
     * Successful Response
     */
    200: Project;
};

export type ProjectServiceGetProjectResponse = ProjectServiceGetProjectResponses[keyof ProjectServiceGetProjectResponses];

export type ProjectServiceUpdateProjectData = {
    body: BodyProjectServiceUpdateProject;
    path?: never;
    query?: never;
    url: '/api/project_service/update_project';
};

export type ProjectServiceUpdateProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProjectServiceUpdateProjectError = ProjectServiceUpdateProjectErrors[keyof ProjectServiceUpdateProjectErrors];

export type ProjectServiceUpdateProjectResponses = {
    /**
     * Successful Response
     */
    200: Project;
};

export type ProjectServiceUpdateProjectResponse = ProjectServiceUpdateProjectResponses[keyof ProjectServiceUpdateProjectResponses];

export type ProjectServiceDeleteProjectData = {
    body: BodyProjectServiceDeleteProject;
    path?: never;
    query?: never;
    url: '/api/project_service/delete_project';
};

export type ProjectServiceDeleteProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProjectServiceDeleteProjectError = ProjectServiceDeleteProjectErrors[keyof ProjectServiceDeleteProjectErrors];

export type ProjectServiceDeleteProjectResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProjectServiceListUserProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/project_service/list_user_projects';
};

export type ProjectServiceListUserProjectsResponses = {
    /**
     * Successful Response
     */
    200: Array<Project>;
};

export type ProjectServiceListUserProjectsResponse = ProjectServiceListUserProjectsResponses[keyof ProjectServiceListUserProjectsResponses];

export type ProjectServiceRefineWithAiData = {
    body: BodyProjectServiceRefineWithAi;
    path?: never;
    query?: never;
    url: '/api/project_service/refine_with_ai';
};

export type ProjectServiceRefineWithAiErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProjectServiceRefineWithAiError = ProjectServiceRefineWithAiErrors[keyof ProjectServiceRefineWithAiErrors];

export type ProjectServiceRefineWithAiResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ProjectServiceRefineWithAiResponse = ProjectServiceRefineWithAiResponses[keyof ProjectServiceRefineWithAiResponses];

export type ProjectServiceSaveStepDataData = {
    body: BodyProjectServiceSaveStepData;
    path?: never;
    query?: never;
    url: '/api/project_service/save_step_data';
};

export type ProjectServiceSaveStepDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProjectServiceSaveStepDataError = ProjectServiceSaveStepDataErrors[keyof ProjectServiceSaveStepDataErrors];

export type ProjectServiceSaveStepDataResponses = {
    /**
     * Successful Response
     */
    200: Project;
};

export type ProjectServiceSaveStepDataResponse = ProjectServiceSaveStepDataResponses[keyof ProjectServiceSaveStepDataResponses];

export type ProjectServiceCompleteProjectData = {
    body: BodyProjectServiceCompleteProject;
    path?: never;
    query?: never;
    url: '/api/project_service/complete_project';
};

export type ProjectServiceCompleteProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProjectServiceCompleteProjectError = ProjectServiceCompleteProjectErrors[keyof ProjectServiceCompleteProjectErrors];

export type ProjectServiceCompleteProjectResponses = {
    /**
     * Successful Response
     */
    200: Project;
};

export type ProjectServiceCompleteProjectResponse = ProjectServiceCompleteProjectResponses[keyof ProjectServiceCompleteProjectResponses];

export type ProjectServiceGetProjectExportData = {
    body: BodyProjectServiceGetProjectExport;
    path?: never;
    query?: never;
    url: '/api/project_service/get_project_export';
};

export type ProjectServiceGetProjectExportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProjectServiceGetProjectExportError = ProjectServiceGetProjectExportErrors[keyof ProjectServiceGetProjectExportErrors];

export type ProjectServiceGetProjectExportResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ProjectServiceGetProjectExportResponse = ProjectServiceGetProjectExportResponses[keyof ProjectServiceGetProjectExportResponses];

export type ProjectServiceGetUserStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/project_service/get_user_stats';
};

export type ProjectServiceGetUserStatsResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ProjectServiceGetUserStatsResponse = ProjectServiceGetUserStatsResponses[keyof ProjectServiceGetUserStatsResponses];

export type FinalDocumentServiceGenerateFinalDocumentData = {
    body: BodyFinalDocumentServiceGenerateFinalDocument;
    path?: never;
    query?: never;
    url: '/api/final_document_service/generate_final_document';
};

export type FinalDocumentServiceGenerateFinalDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FinalDocumentServiceGenerateFinalDocumentError = FinalDocumentServiceGenerateFinalDocumentErrors[keyof FinalDocumentServiceGenerateFinalDocumentErrors];

export type FinalDocumentServiceGenerateFinalDocumentResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type FinalDocumentServiceGenerateFinalDocumentResponse = FinalDocumentServiceGenerateFinalDocumentResponses[keyof FinalDocumentServiceGenerateFinalDocumentResponses];

export type FinalDocumentServiceGetProjectSummaryData = {
    body: BodyFinalDocumentServiceGetProjectSummary;
    path?: never;
    query?: never;
    url: '/api/final_document_service/get_project_summary';
};

export type FinalDocumentServiceGetProjectSummaryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FinalDocumentServiceGetProjectSummaryError = FinalDocumentServiceGetProjectSummaryErrors[keyof FinalDocumentServiceGetProjectSummaryErrors];

export type FinalDocumentServiceGetProjectSummaryResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type FinalDocumentServiceGetProjectSummaryResponse = FinalDocumentServiceGetProjectSummaryResponses[keyof FinalDocumentServiceGetProjectSummaryResponses];